### ISSUE TITLE
Lege main

### ISSUE THREAD

**Issue by RichardRam87** [SebastiaanBuwalda/XMLDialogSystem#2]
Je hebt feedback gekregen van **RichardRam87**
URL: https://github.com/SebastiaanBuwalda/XMLDialogSystem/blob/master/Scripts/main.js

Feedback: Probeer je main zo leeg mogelijk te houden. Preload alle nodige scenes en load de scene die vervolgens je applicatie als eerste moet uitvoeren.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"0077630fc71c63784557efc829f65ea7afc17abf","path":"Scripts/main.js","reviewer":"RichardRam87"}')

**Comment by SebastiaanBuwalda** [comment]
Gefixed.
