### ISSUE TITLE
Betere benaming

### ISSUE THREAD

**Issue by RichardRam87** [SebastiaanBuwalda/XMLDialogSystem#3]
Je hebt feedback gekregen van **RichardRam87**
op:
```c
  textFunctions.advanceText(); 
```

URL: https://github.com/SebastiaanBuwalda/XMLDialogSystem/blob/master/Scripts/main.js

Feedback: geef dit prototype een betere benaming[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"0077630fc71c63784557efc829f65ea7afc17abf","path":"Scripts/main.js","reviewer":"RichardRam87"}')

**Comment by SebastiaanBuwalda** [comment]
Fixed
